language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install valgrind

script:
  - make
  - ./json_unit "*"
  - valgrind --error-exitcode=1 --leak-check=full ./main

after_success:
  - make clean
